// <auto-generated />
using System;
using LeohootBackend;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace leohoot_backend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240118134205_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("LeohootBackend.Model.Answer", b =>
                {
                    b.Property<int>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.HasKey("AnswerId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("LeohootBackend.Model.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnswerTimeInSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("NextQuestionQuestionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PreviewTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("QuestionId");

                    b.HasIndex("NextQuestionQuestionId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("LeohootBackend.Model.Quiz", b =>
                {
                    b.Property<int>("QuizId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UsernameCreator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("QuizId");

                    b.HasIndex("UsernameCreator");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("LeohootBackend.Model.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Username");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LeohootBackend.Model.Answer", b =>
                {
                    b.HasOne("LeohootBackend.Model.Question", null)
                        .WithMany("Answers")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LeohootBackend.Model.Question", b =>
                {
                    b.HasOne("LeohootBackend.Model.Question", "NextQuestion")
                        .WithMany()
                        .HasForeignKey("NextQuestionQuestionId");

                    b.HasOne("LeohootBackend.Model.Quiz", null)
                        .WithMany("Questions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NextQuestion");
                });

            modelBuilder.Entity("LeohootBackend.Model.Quiz", b =>
                {
                    b.HasOne("LeohootBackend.Model.User", "Creator")
                        .WithMany()
                        .HasForeignKey("UsernameCreator")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("LeohootBackend.Model.Question", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("LeohootBackend.Model.Quiz", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
