entryPoints:
  web:
    address: ":80"
    forwardedHeaders:
      insecure: true
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"
    forwardedHeaders:
      insecure: true
    http:
      tls:
        certresolver: leohootresolver

api:
  insecure: false
  dashboard: false

log:
  level: "DEBUG"

providers:
  docker:
    exposedByDefault: false
    watch: true

  file:
    directory: /etc/traefik/custom/
    watch: true

certificatesResolvers:
  leohootresolver:
    acme:
      email: "sophiehaider06@gmail.com"
      storage: "/letsencrypt/acme.json"
      httpChallenge:
        entryPoint: web